# Generated by Django 5.0.3 on 2024-03-10 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='content',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
